/**
 * Practicar cada fila de kana (ej. さしすせそ) en oraciones cortas reales,
 * no sueltas — para reconocerla escuchando y tocando el caracter correcto,
 * no solo memorizarla aislada. Mecánica tipo Duolingo "escuchá y
 * seleccioná": se escucha la oración completa, se arma tocando fichas de
 * kana en el orden que suenan (banco = fichas correctas + distractores),
 * cada ficha también suena sola al tocarla para poder verificar de oído
 * antes de confirmar.
 *
 * Cubre las 10 filas básicas del gojūon (あかたなはまやらわん) MÁS dakuten
 * (がざだばぱ) y yōon (きゃしゃちゃにゃひゃみゃりゃぎゃじゃびゃぴゃ) en
 * hiragana y katakana — el set completo de `/caracteres` (básico + avanzado).
 * Curado a mano, mismo criterio que gramática y `/temas`: oraciones N5
 * reales (no inventadas), sin espacios entre palabras — el japonés no los
 * usa. No restringidas a "solo kana ya visto en filas anteriores" (eso
 * volvería todo artificial, です mismo usa で, de la fila た); el criterio es
 * que la fila objetivo aparezca seguido, no que sea lo único presente.
 *
 * Varias filas tienen MUY poco vocabulario real disponible — algunas casi
 * nada (みゃ, ぴゃ en hiragana; プレゼント excluida de katakana por lo mismo
 * en varias filas de yōon). Ahí el pool queda deliberadamente chico (2-4
 * oraciones) en vez de forzar ejemplos artificiales o mal formados — y
 * cuando ni eso alcanza para un pool honesto (ej. リャ o ギャ en préstamos
 * del inglés), la fila directamente no está: hueco documentado > contenido
 * de baja precisión. Katakana ya/わ/ん también tienen pools chicos por la
 * misma razón (ヲ casi no se usa, ヤユヨ dan pocas palabras extranjeras).
 *
 * El pool de cada fila es más grande que una sesión (`SESSION_SIZE`) para
 * que "otra sesión" con la misma fila muestre una mezcla distinta, no
 * exactamente lo mismo — salvo en las filas más chicas, donde el pool
 * entero cabe en una sola sesión.
 */

import type { Localized } from '@/lib/i18n/localized';

export type KanaSentence = {
  id: string;
  /** Oración en hiragana/katakana, sin kanji ni espacios — recién arrancando el silabario. */
  jp: string;
  /** Lectura en alfabeto latino. */
  reading: string;
  /** Traducción simple — se revela recién al confirmar. */
  translation: Localized;
};

export type KanaRowPractice = {
  /** Id de la fila, igual al `row` de kana-data.ts (ej. "sa"). */
  id: string;
  kind: 'hiragana' | 'katakana';
  /** Los caracteres de la fila, para mostrar en el título (ej. "さしすせそ"). */
  chars: string;
  sentences: KanaSentence[];
};

export const SESSION_SIZE = 8;

export const KANA_ROW_PRACTICE: KanaRowPractice[] = [
  {
    id: 'hiragana-a',
    kind: 'hiragana',
    chars: 'あいうえお',
    sentences: [
      { id: 'ha1', jp: 'あめがふります。', reading: 'ame ga furimasu.', translation: { es: 'Llueve.', en: 'It\'s raining.' } },
      { id: 'ha2', jp: 'いえにかえります。', reading: 'ie ni kaerimasu.', translation: { es: 'Vuelvo a casa.', en: 'I go back home.' } },
      { id: 'ha3', jp: 'うみがすきです。', reading: 'umi ga suki desu.', translation: { es: 'Me gusta el mar.', en: 'I like the sea.' } },
      { id: 'ha4', jp: 'えいがをみます。', reading: 'eiga wo mimasu.', translation: { es: 'Veo una película.', en: 'I watch a movie.' } },
      { id: 'ha5', jp: 'おちゃをのみます。', reading: 'ocha wo nomimasu.', translation: { es: 'Tomo té.', en: 'I drink tea.' } },
      { id: 'ha6', jp: 'あさごはんをたべます。', reading: 'asagohan wo tabemasu.', translation: { es: 'Como el desayuno.', en: 'I eat breakfast.' } },
      { id: 'ha7', jp: 'いぬがいます。', reading: 'inu ga imasu.', translation: { es: 'Hay un perro.', en: 'There is a dog.' } },
      { id: 'ha8', jp: 'うたをうたいます。', reading: 'uta wo utaimasu.', translation: { es: 'Canto una canción.', en: 'I sing a song.' } },
      { id: 'ha9', jp: 'えきまであるきます。', reading: 'eki made arukimasu.', translation: { es: 'Camino hasta la estación.', en: 'I walk to the station.' } },
      { id: 'ha10', jp: 'おおきいいえです。', reading: 'ookii ie desu.', translation: { es: 'Es una casa grande.', en: 'It is a big house.' } },
    ],
  },
  {
    id: 'hiragana-ka',
    kind: 'hiragana',
    chars: 'かきくけこ',
    sentences: [
      { id: 'hka1', jp: 'かさをかいました。', reading: 'kasa wo kaimashita.', translation: { es: 'Compré un paraguas.', en: 'I bought an umbrella.' } },
      { id: 'hka2', jp: 'きれいなはなです。', reading: 'kirei na hana desu.', translation: { es: 'Es una flor linda.', en: 'It is a pretty flower.' } },
      { id: 'hka3', jp: 'くるまでいきます。', reading: 'kuruma de ikimasu.', translation: { es: 'Voy en auto.', en: 'I go by car.' } },
      { id: 'hka4', jp: 'けさはさむいです。', reading: 'kesa wa samui desu.', translation: { es: 'Esta mañana hace frío.', en: 'It\'s cold this morning.' } },
      { id: 'hka5', jp: 'こどもがすきです。', reading: 'kodomo ga suki desu.', translation: { es: 'Me gustan los niños.', en: 'I like children.' } },
      { id: 'hka6', jp: 'かいしゃにいきます。', reading: 'kaisha ni ikimasu.', translation: { es: 'Voy a la oficina.', en: 'I go to the office.' } },
      { id: 'hka7', jp: 'かぎをなくしました。', reading: 'kagi wo nakushimashita.', translation: { es: 'Perdí la llave.', en: 'I lost the key.' } },
      { id: 'hka8', jp: 'くつをはきます。', reading: 'kutsu wo hakimasu.', translation: { es: 'Me pongo los zapatos.', en: 'I put on my shoes.' } },
      { id: 'hka9', jp: 'けいたいをわすれました。', reading: 'keitai wo wasuremashita.', translation: { es: 'Me olvidé el celular.', en: 'I forgot my phone.' } },
      { id: 'hka10', jp: 'こうえんであそびます。', reading: 'kouen de asobimasu.', translation: { es: 'Juego en el parque.', en: 'I play in the park.' } },
    ],
  },
  {
    id: 'hiragana-ta',
    kind: 'hiragana',
    chars: 'たちつてと',
    sentences: [
      { id: 'hta1', jp: 'たかいたてものです。', reading: 'takai tatemono desu.', translation: { es: 'Es un edificio alto.', en: 'It is a tall building.' } },
      { id: 'hta2', jp: 'ちいさいねこです。', reading: 'chiisai neko desu.', translation: { es: 'Es un gato pequeño.', en: 'It is a small cat.' } },
      { id: 'hta3', jp: 'つくえのうえにあります。', reading: 'tsukue no ue ni arimasu.', translation: { es: 'Está sobre el escritorio.', en: 'It\'s on the desk.' } },
      { id: 'hta4', jp: 'てがみをかきます。', reading: 'tegami wo kakimasu.', translation: { es: 'Escribo una carta.', en: 'I write a letter.' } },
      { id: 'hta5', jp: 'ともだちにあいます。', reading: 'tomodachi ni aimasu.', translation: { es: 'Me encuentro con un amigo.', en: 'I meet with a friend.' } },
      { id: 'hta6', jp: 'たべものがおおいです。', reading: 'tabemono ga ooi desu.', translation: { es: 'Hay mucha comida.', en: 'There is a lot of food.' } },
      { id: 'hta7', jp: 'ちかてつでいきます。', reading: 'chikatetsu de ikimasu.', translation: { es: 'Voy en metro.', en: 'I go by subway.' } },
      { id: 'hta8', jp: 'つめたいみずをのみます。', reading: 'tsumetai mizu wo nomimasu.', translation: { es: 'Tomo agua fría.', en: 'I drink cold water.' } },
      { id: 'hta9', jp: 'てんきがいいです。', reading: 'tenki ga ii desu.', translation: { es: 'El clima está bueno.', en: 'The weather is good.' } },
      { id: 'hta10', jp: 'とけいをかいました。', reading: 'tokei wo kaimashita.', translation: { es: 'Compré un reloj.', en: 'I bought a watch.' } },
    ],
  },
  {
    id: 'hiragana-na',
    kind: 'hiragana',
    chars: 'なにぬねの',
    sentences: [
      { id: 'hna1', jp: 'なつがすきです。', reading: 'natsu ga suki desu.', translation: { es: 'Me gusta el verano.', en: 'I like summer.' } },
      { id: 'hna2', jp: 'にほんごをべんきょうします。', reading: 'nihongo wo benkyoushimasu.', translation: { es: 'Estudio japonés.', en: 'I study Japanese.' } },
      { id: 'hna3', jp: 'ぬのでつくりました。', reading: 'nuno de tsukurimashita.', translation: { es: 'Lo hice con tela.', en: 'I made it with fabric.' } },
      { id: 'hna4', jp: 'ねこがねています。', reading: 'neko ga neteimasu.', translation: { es: 'El gato está durmiendo.', en: 'The cat is sleeping.' } },
      { id: 'hna5', jp: 'のみものをください。', reading: 'nomimono wo kudasai.', translation: { es: 'Una bebida, por favor.', en: 'A drink, please.' } },
      { id: 'hna6', jp: 'なまえをかいてください。', reading: 'namae wo kaite kudasai.', translation: { es: 'Escriba su nombre, por favor.', en: 'Write your name, please.' } },
      { id: 'hna7', jp: 'にわにはながあります。', reading: 'niwa ni hana ga arimasu.', translation: { es: 'Hay flores en el jardín.', en: 'There are flowers in the garden.' } },
      { id: 'hna8', jp: 'ぬいぐるみがすきです。', reading: 'nuigurumi ga suki desu.', translation: { es: 'Me gustan los peluches.', en: 'I like stuffed animals.' } },
      { id: 'hna9', jp: 'ねだんがたかいです。', reading: 'nedan ga takai desu.', translation: { es: 'El precio es caro.', en: 'The price is expensive.' } },
      { id: 'hna10', jp: 'のどがかわきました。', reading: 'nodo ga kawakimashita.', translation: { es: 'Tengo sed.', en: 'I am thirsty.' } },
    ],
  },
  {
    id: 'hiragana-ha',
    kind: 'hiragana',
    chars: 'はひふへほ',
    sentences: [
      { id: 'hha1', jp: 'はなびがきれいです。', reading: 'hanabi ga kirei desu.', translation: { es: 'Los fuegos artificiales son lindos.', en: 'The fireworks are pretty.' } },
      { id: 'hha2', jp: 'ひこうきにのります。', reading: 'hikouki ni norimasu.', translation: { es: 'Subo a un avión.', en: 'I board a plane.' } },
      { id: 'hha3', jp: 'ふゆはさむいです。', reading: 'fuyu wa samui desu.', translation: { es: 'El invierno es frío.', en: 'Winter is cold.' } },
      { id: 'hha4', jp: 'へやをそうじします。', reading: 'heya wo souji shimasu.', translation: { es: 'Limpio el cuarto.', en: 'I clean the room.' } },
      { id: 'hha5', jp: 'ほんをよみます。', reading: 'hon wo yomimasu.', translation: { es: 'Leo un libro.', en: 'I read a book.' } },
      { id: 'hha6', jp: 'はやくきてください。', reading: 'hayaku kite kudasai.', translation: { es: 'Venga rápido, por favor.', en: 'Come quickly, please.' } },
      { id: 'hha7', jp: 'ひとがおおいです。', reading: 'hito ga ooi desu.', translation: { es: 'Hay mucha gente.', en: 'There are a lot of people.' } },
      { id: 'hha8', jp: 'ふくをかいました。', reading: 'fuku wo kaimashita.', translation: { es: 'Compré ropa.', en: 'I bought clothes.' } },
      { id: 'hha9', jp: 'へたですががんばります。', reading: 'heta desu ga ganbarimasu.', translation: { es: 'No soy bueno, pero me esfuerzo.', en: 'I\'m not good, but I try hard.' } },
      { id: 'hha10', jp: 'ほしがきれいです。', reading: 'hoshi ga kirei desu.', translation: { es: 'Las estrellas son lindas.', en: 'The stars are pretty.' } },
    ],
  },
  {
    id: 'hiragana-ma',
    kind: 'hiragana',
    chars: 'まみむめも',
    sentences: [
      { id: 'hma1', jp: 'まいにちはしります。', reading: 'mainichi hashirimasu.', translation: { es: 'Corro todos los días.', en: 'I run every day.' } },
      { id: 'hma2', jp: 'みずをください。', reading: 'mizu wo kudasai.', translation: { es: 'Agua, por favor.', en: 'Water, please.' } },
      { id: 'hma3', jp: 'むずかしいもんだいです。', reading: 'muzukashii mondai desu.', translation: { es: 'Es un problema difícil.', en: 'It is a difficult problem.' } },
      { id: 'hma4', jp: 'めがいたいです。', reading: 'me ga itai desu.', translation: { es: 'Me duelen los ojos.', en: 'My eyes hurt.' } },
      { id: 'hma5', jp: 'ものがたりをよみます。', reading: 'monogatari wo yomimasu.', translation: { es: 'Leo un cuento.', en: 'I read a story.' } },
      { id: 'hma6', jp: 'まどをあけてください。', reading: 'mado wo akete kudasai.', translation: { es: 'Abra la ventana, por favor.', en: 'Open the window, please.' } },
      { id: 'hma7', jp: 'みちがわかりません。', reading: 'michi ga wakarimasen.', translation: { es: 'No sé el camino.', en: 'I don\'t know the way.' } },
      { id: 'hma8', jp: 'むかしのはなしです。', reading: 'mukashi no hanashi desu.', translation: { es: 'Es una historia antigua.', en: 'It is an old story.' } },
      { id: 'hma9', jp: 'めがねをかけます。', reading: 'megane wo kakemasu.', translation: { es: 'Me pongo los anteojos.', en: 'I put on my glasses.' } },
      { id: 'hma10', jp: 'もんだいありません。', reading: 'mondai arimasen.', translation: { es: 'No hay problema.', en: 'There is no problem.' } },
    ],
  },
  {
    id: 'hiragana-ya',
    kind: 'hiragana',
    chars: 'やゆよ',
    sentences: [
      { id: 'hya1', jp: 'やさいがすきです。', reading: 'yasai ga suki desu.', translation: { es: 'Me gustan las verduras.', en: 'I like vegetables.' } },
      { id: 'hya2', jp: 'ゆきがふっています。', reading: 'yuki ga futteimasu.', translation: { es: 'Está nevando.', en: 'It\'s snowing.' } },
      { id: 'hya3', jp: 'よるはしずかです。', reading: 'yoru wa shizuka desu.', translation: { es: 'La noche es tranquila.', en: 'The night is quiet.' } },
      { id: 'hya4', jp: 'やすみがほしいです。', reading: 'yasumi ga hoshii desu.', translation: { es: 'Quiero un descanso.', en: 'I want a break.' } },
      { id: 'hya5', jp: 'ゆうめいなひとです。', reading: 'yuumei na hito desu.', translation: { es: 'Es una persona famosa.', en: 'He/She is a famous person.' } },
      { id: 'hya6', jp: 'よやくをしました。', reading: 'yoyaku wo shimashita.', translation: { es: 'Hice una reserva.', en: 'I made a reservation.' } },
      { id: 'hya7', jp: 'やまにのぼります。', reading: 'yama ni noborimasu.', translation: { es: 'Subo a la montaña.', en: 'I climb the mountain.' } },
      { id: 'hya8', jp: 'ゆびがいたいです。', reading: 'yubi ga itai desu.', translation: { es: 'Me duele el dedo.', en: 'My finger hurts.' } },
      { id: 'hya9', jp: 'よていがあります。', reading: 'yotei ga arimasu.', translation: { es: 'Tengo planes.', en: 'I have plans.' } },
      { id: 'hya10', jp: 'やちんがたかいです。', reading: 'yachin ga takai desu.', translation: { es: 'El alquiler es caro.', en: 'The rent is expensive.' } },
    ],
  },
  {
    id: 'hiragana-ra',
    kind: 'hiragana',
    chars: 'らりるれろ',
    sentences: [
      { id: 'hra1', jp: 'らいねんにほんへいきます。', reading: 'rainen nihon e ikimasu.', translation: { es: 'El año que viene voy a Japón.', en: 'Next year I am going to Japan.' } },
      { id: 'hra2', jp: 'りんごをたべます。', reading: 'ringo wo tabemasu.', translation: { es: 'Como una manzana.', en: 'I eat an apple.' } },
      { id: 'hra3', jp: 'るすです。', reading: 'rusu desu.', translation: { es: 'No está en casa.', en: 'He/She isn\'t home.' } },
      { id: 'hra4', jp: 'れいぞうこにあります。', reading: 'reizouko ni arimasu.', translation: { es: 'Está en la heladera.', en: 'It\'s in the fridge.' } },
      { id: 'hra5', jp: 'ろうかをあるきます。', reading: 'rouka wo arukimasu.', translation: { es: 'Camino por el pasillo.', en: 'I walk down the hallway.' } },
      { id: 'hra6', jp: 'らくなしごとです。', reading: 'raku na shigoto desu.', translation: { es: 'Es un trabajo fácil.', en: 'It is an easy job.' } },
      { id: 'hra7', jp: 'りゆうがわかりません。', reading: 'riyuu ga wakarimasen.', translation: { es: 'No entiendo la razón.', en: 'I don\'t understand the reason.' } },
      { id: 'hra8', jp: 'るーるをまもります。', reading: 'ruuru wo mamorimasu.', translation: { es: 'Sigo las reglas.', en: 'I follow the rules.' } },
      { id: 'hra9', jp: 'れきしがすきです。', reading: 'rekishi ga suki desu.', translation: { es: 'Me gusta la historia.', en: 'I like history.' } },
      { id: 'hra10', jp: 'ろくじにおきます。', reading: 'rokuji ni okimasu.', translation: { es: 'Me levanto a las 6.', en: 'I get up at 6.' } },
    ],
  },
  {
    id: 'hiragana-wa',
    kind: 'hiragana',
    chars: 'わを',
    sentences: [
      { id: 'hwa1', jp: 'わたしはがくせいです。', reading: 'watashi wa gakusei desu.', translation: { es: 'Yo soy estudiante.', en: 'I am a student.' } },
      { id: 'hwa2', jp: 'これをください。', reading: 'kore wo kudasai.', translation: { es: 'Esto, por favor.', en: 'This, please.' } },
      { id: 'hwa3', jp: 'わすれものをしました。', reading: 'wasuremono wo shimashita.', translation: { es: 'Me olvidé algo.', en: 'I forgot something.' } },
      { id: 'hwa4', jp: 'わかりました。', reading: 'wakarimashita.', translation: { es: 'Entendido.', en: 'Understood.' } },
      { id: 'hwa5', jp: 'ほんをよみました。', reading: 'hon wo yomimashita.', translation: { es: 'Leí un libro.', en: 'I read a book.' } },
      { id: 'hwa6', jp: 'わらいました。', reading: 'waraimashita.', translation: { es: 'Me reí.', en: 'I laughed.' } },
      { id: 'hwa7', jp: 'わるいてんきです。', reading: 'warui tenki desu.', translation: { es: 'Es mal clima.', en: 'It\'s bad weather.' } },
      { id: 'hwa8', jp: 'おさけをのみました。', reading: 'osake wo nomimashita.', translation: { es: 'Tomé alcohol.', en: 'I drank alcohol.' } },
      { id: 'hwa9', jp: 'わたしのかばんです。', reading: 'watashi no kaban desu.', translation: { es: 'Es mi bolso.', en: 'It is my bag.' } },
      { id: 'hwa10', jp: 'でんわをかけます。', reading: 'denwa wo kakemasu.', translation: { es: 'Hago una llamada.', en: 'I make a call.' } },
    ],
  },
  {
    id: 'hiragana-n',
    kind: 'hiragana',
    chars: 'ん',
    sentences: [
      { id: 'hn1', jp: 'ほんがたくさんあります。', reading: 'hon ga takusan arimasu.', translation: { es: 'Hay muchos libros.', en: 'There are many books.' } },
      { id: 'hn2', jp: 'せんせいにききました。', reading: 'sensei ni kikimashita.', translation: { es: 'Le pregunté al profesor.', en: 'I asked the teacher.' } },
      { id: 'hn3', jp: 'でんしゃにのります。', reading: 'densha ni norimasu.', translation: { es: 'Subo al tren.', en: 'I get on the train.' } },
      { id: 'hn4', jp: 'にほんごをはなします。', reading: 'nihongo wo hanashimasu.', translation: { es: 'Hablo japonés.', en: 'I speak Japanese.' } },
      { id: 'hn5', jp: 'ぜんぶたべました。', reading: 'zenbu tabemashita.', translation: { es: 'Comí todo.', en: 'I ate everything.' } },
      { id: 'hn6', jp: 'あんぜんです。', reading: 'anzen desu.', translation: { es: 'Es seguro.', en: 'It is safe.' } },
      { id: 'hn7', jp: 'しんぶんをよみます。', reading: 'shinbun wo yomimasu.', translation: { es: 'Leo el diario.', en: 'I read the newspaper.' } },
      { id: 'hn8', jp: 'けんこうがだいじです。', reading: 'kenkou ga daiji desu.', translation: { es: 'La salud es importante.', en: 'Health is important.' } },
      { id: 'hn9', jp: 'うんどうをします。', reading: 'undou wo shimasu.', translation: { es: 'Hago ejercicio.', en: 'I exercise.' } },
      { id: 'hn10', jp: 'しんせつなひとです。', reading: 'shinsetsu na hito desu.', translation: { es: 'Es una persona amable.', en: 'He/She is a kind person.' } },
    ],
  },
  {
    id: 'hiragana-ga',
    kind: 'hiragana',
    chars: 'がぎぐげご',
    sentences: [
      { id: 'hga1', jp: 'がっこうにいきます。', reading: 'gakkou ni ikimasu.', translation: { es: 'Voy a la escuela.', en: 'I go to school.' } },
      { id: 'hga2', jp: 'かぎをわすれました。', reading: 'kagi wo wasuremashita.', translation: { es: 'Me olvidé la llave.', en: 'I forgot the key.' } },
      { id: 'hga3', jp: 'ぐあいがわるいです。', reading: 'guai ga warui desu.', translation: { es: 'Me siento mal.', en: 'I feel bad.' } },
      { id: 'hga4', jp: 'げんきですか。', reading: 'genki desu ka.', translation: { es: '¿Cómo estás?', en: 'How are you?' } },
      { id: 'hga5', jp: 'ごはんをたべます。', reading: 'gohan wo tabemasu.', translation: { es: 'Como arroz.', en: 'I eat rice.' } },
      { id: 'hga6', jp: 'えいごをはなします。', reading: 'eigo wo hanashimasu.', translation: { es: 'Hablo inglés.', en: 'I speak English.' } },
      { id: 'hga7', jp: 'かがみをみます。', reading: 'kagami wo mimasu.', translation: { es: 'Me miro al espejo.', en: 'I look in the mirror.' } },
      { id: 'hga8', jp: 'すごいですね。', reading: 'sugoi desu ne.', translation: { es: '¡Qué genial!', en: 'How great!' } },
    ],
  },
  {
    id: 'hiragana-za',
    kind: 'hiragana',
    chars: 'ざじずぜぞ',
    sentences: [
      { id: 'hza1', jp: 'ざんねんです。', reading: 'zannen desu.', translation: { es: 'Qué lástima.', en: 'That\'s a shame.' } },
      { id: 'hza2', jp: 'じかんがありません。', reading: 'jikan ga arimasen.', translation: { es: 'No tengo tiempo.', en: 'I don\'t have time.' } },
      { id: 'hza3', jp: 'かぜをひきました。', reading: 'kaze wo hikimashita.', translation: { es: 'Me resfrié.', en: 'I caught a cold.' } },
      { id: 'hza4', jp: 'ぜんぶわかりました。', reading: 'zenbu wakarimashita.', translation: { es: 'Entendí todo.', en: 'I understood everything.' } },
      { id: 'hza5', jp: 'ぞうがいます。', reading: 'zou ga imasu.', translation: { es: 'Hay un elefante.', en: 'There is an elephant.' } },
      { id: 'hza6', jp: 'ざっしをよみます。', reading: 'zasshi wo yomimasu.', translation: { es: 'Leo una revista.', en: 'I read a magazine.' } },
      { id: 'hza7', jp: 'じしょをつかいます。', reading: 'jisho wo tsukaimasu.', translation: { es: 'Uso el diccionario.', en: 'I use the dictionary.' } },
      { id: 'hza8', jp: 'しずかなばしょです。', reading: 'shizuka na basho desu.', translation: { es: 'Es un lugar tranquilo.', en: 'It is a quiet place.' } },
    ],
  },
  {
    id: 'hiragana-da',
    kind: 'hiragana',
    chars: 'だぢづでど',
    sentences: [
      { id: 'hda1', jp: 'だいじょうぶです。', reading: 'daijoubu desu.', translation: { es: 'Está bien.', en: 'It\'s fine.' } },
      { id: 'hda2', jp: 'でんしゃがおくれました。', reading: 'densha ga okuremashita.', translation: { es: 'El tren se atrasó.', en: 'The train was delayed.' } },
      { id: 'hda3', jp: 'どようびにあいましょう。', reading: 'doyoubi ni aimashou.', translation: { es: 'Veámonos el sábado.', en: 'Let\'s meet on Saturday.' } },
      { id: 'hda4', jp: 'だれもいません。', reading: 'dare mo imasen.', translation: { es: 'No hay nadie.', en: 'There is no one.' } },
      { id: 'hda5', jp: 'どこにいますか。', reading: 'doko ni imasu ka.', translation: { es: '¿Dónde estás?', en: 'Where are you?' } },
      { id: 'hda6', jp: 'でかけます。', reading: 'dekakemasu.', translation: { es: 'Salgo de casa.', en: 'I leave home.' } },
      { id: 'hda7', jp: 'だいすきです。', reading: 'daisuki desu.', translation: { es: 'Me encanta.', en: 'I love it.' } },
      { id: 'hda8', jp: 'どうぶつがすきです。', reading: 'doubutsu ga suki desu.', translation: { es: 'Me gustan los animales.', en: 'I like animals.' } },
    ],
  },
  {
    id: 'hiragana-ba',
    kind: 'hiragana',
    chars: 'ばびぶべぼ',
    sentences: [
      { id: 'hba1', jp: 'ばんごはんをたべます。', reading: 'bangohan wo tabemasu.', translation: { es: 'Como la cena.', en: 'I eat dinner.' } },
      { id: 'hba2', jp: 'かばんをかいました。', reading: 'kaban wo kaimashita.', translation: { es: 'Compré un bolso.', en: 'I bought a bag.' } },
      { id: 'hba3', jp: 'ぶたにくがすきです。', reading: 'butaniku ga suki desu.', translation: { es: 'Me gusta la carne de cerdo.', en: 'I like pork.' } },
      { id: 'hba4', jp: 'べんきょうします。', reading: 'benkyou shimasu.', translation: { es: 'Estudio.', en: 'I study.' } },
      { id: 'hba5', jp: 'ぼうしをかぶります。', reading: 'boushi wo kaburimasu.', translation: { es: 'Me pongo el sombrero.', en: 'I put on the hat.' } },
      { id: 'hba6', jp: 'たばこをすいません。', reading: 'tabako wo suimasen.', translation: { es: 'No fumo.', en: 'I don\'t smoke.' } },
      { id: 'hba7', jp: 'そばやにいきます。', reading: 'sobaya ni ikimasu.', translation: { es: 'Voy a una fideería.', en: 'I go to a noodle shop.' } },
      { id: 'hba8', jp: 'ばんぐみをみます。', reading: 'bangumi wo mimasu.', translation: { es: 'Veo un programa de TV.', en: 'I watch a TV show.' } },
    ],
  },
  {
    id: 'hiragana-pa',
    kind: 'hiragana',
    chars: 'ぱぴぷぺぽ',
    sentences: [
      { id: 'hpa1', jp: 'おなかがぺこぺこです。', reading: 'onaka ga pekopeko desu.', translation: { es: 'Tengo mucha hambre.', en: 'I am very hungry.' } },
      { id: 'hpa2', jp: 'ほしがぴかぴかです。', reading: 'hoshi ga pikapika desu.', translation: { es: 'Las estrellas brillan.', en: 'The stars shine.' } },
      { id: 'hpa3', jp: 'てんきがぽかぽかです。', reading: 'tenki ga pokapoka desu.', translation: { es: 'El clima está calentito.', en: 'The weather is nice and warm.' } },
      { id: 'hpa4', jp: 'おこってぷんぷんしています。', reading: 'okotte punpun shiteimasu.', translation: { es: 'Está enojado.', en: 'He is angry.' } },
      { id: 'hpa5', jp: 'ぱくぱくたべます。', reading: 'pakupaku tabemasu.', translation: { es: 'Come vorazmente.', en: 'He eats voraciously.' } },
    ],
  },
  {
    id: 'hiragana-kya',
    kind: 'hiragana',
    chars: 'きゃきゅきょ',
    sentences: [
      { id: 'hkya1', jp: 'きょうはいそがしいです。', reading: 'kyou wa isogashii desu.', translation: { es: 'Hoy estoy ocupado.', en: 'I am busy today.' } },
      { id: 'hkya2', jp: 'きゅうにあめがふりました。', reading: 'kyuu ni ame ga furimashita.', translation: { es: 'De repente llovió.', en: 'It suddenly rained.' } },
      { id: 'hkya3', jp: 'おきゃくさんがきました。', reading: 'okyakusan ga kimashita.', translation: { es: 'Vino un cliente.', en: 'A customer came.' } },
      { id: 'hkya4', jp: 'きょうしつはひろいです。', reading: 'kyoushitsu wa hiroi desu.', translation: { es: 'El salón de clases es grande.', en: 'The classroom is big.' } },
      { id: 'hkya5', jp: 'きゅうりょうがはいりました。', reading: 'kyuuryou ga hairimashita.', translation: { es: 'Me depositaron el sueldo.', en: 'My salary was deposited.' } },
      { id: 'hkya6', jp: 'きょねんにほんへいきました。', reading: 'kyonen nihon e ikimashita.', translation: { es: 'El año pasado fui a Japón.', en: 'Last year I went to Japan.' } },
      { id: 'hkya7', jp: 'きゅうけいしましょう。', reading: 'kyuukei shimashou.', translation: { es: 'Descansemos.', en: 'Let\'s rest.' } },
      { id: 'hkya8', jp: 'おきゃくさまをごあんないします。', reading: 'okyakusama wo goannai shimasu.', translation: { es: 'Guío al cliente.', en: 'I guide the customer.' } },
    ],
  },
  {
    id: 'hiragana-sha',
    kind: 'hiragana',
    chars: 'しゃしゅしょ',
    sentences: [
      { id: 'hsha1', jp: 'しゃしんをとります。', reading: 'shashin wo torimasu.', translation: { es: 'Saco una foto.', en: 'I take a photo.' } },
      { id: 'hsha2', jp: 'しゅくだいをします。', reading: 'shukudai wo shimasu.', translation: { es: 'Hago la tarea.', en: 'I do homework.' } },
      { id: 'hsha3', jp: 'しょうがっこうにいきます。', reading: 'shougakkou ni ikimasu.', translation: { es: 'Voy a la primaria.', en: 'I go to elementary school.' } },
      { id: 'hsha4', jp: 'しゃちょうにあいます。', reading: 'shachou ni aimasu.', translation: { es: 'Me encuentro con el jefe.', en: 'I meet with the boss.' } },
      { id: 'hsha5', jp: 'しゅみはなんですか。', reading: 'shumi wa nan desu ka.', translation: { es: '¿Cuál es tu hobby?', en: 'What\'s your hobby?' } },
      { id: 'hsha6', jp: 'しょくじをします。', reading: 'shokuji wo shimasu.', translation: { es: 'Como una comida.', en: 'I eat a meal.' } },
      { id: 'hsha7', jp: 'しゃかいがかわります。', reading: 'shakai ga kawarimasu.', translation: { es: 'La sociedad cambia.', en: 'Society changes.' } },
      { id: 'hsha8', jp: 'じしょがひつようです。', reading: 'jisho ga hitsuyou desu.', translation: { es: 'Necesito un diccionario.', en: 'I need a dictionary.' } },
    ],
  },
  {
    id: 'hiragana-cha',
    kind: 'hiragana',
    chars: 'ちゃちゅちょ',
    sentences: [
      { id: 'hcha1', jp: 'おちゃをのみます。', reading: 'ocha wo nomimasu.', translation: { es: 'Tomo té.', en: 'I drink tea.' } },
      { id: 'hcha2', jp: 'ちゅうしゃじょうはどこですか。', reading: 'chuushajou wa doko desu ka.', translation: { es: '¿Dónde está el estacionamiento?', en: 'Where is the parking lot?' } },
      { id: 'hcha3', jp: 'ちょうどいいです。', reading: 'choudo ii desu.', translation: { es: 'Está justo bien.', en: 'It\'s just right.' } },
      { id: 'hcha4', jp: 'ちゃいろがすきです。', reading: 'chairo ga suki desu.', translation: { es: 'Me gusta el color marrón.', en: 'I like the color brown.' } },
      { id: 'hcha5', jp: 'ちゅうごくごをはなします。', reading: 'chuugokugo wo hanashimasu.', translation: { es: 'Hablo chino.', en: 'I speak Chinese.' } },
      { id: 'hcha6', jp: 'ちょきんをします。', reading: 'chokin wo shimasu.', translation: { es: 'Ahorro dinero.', en: 'I save money.' } },
      { id: 'hcha7', jp: 'おもちゃがすきです。', reading: 'omocha ga suki desu.', translation: { es: 'Me gustan los juguetes.', en: 'I like toys.' } },
      { id: 'hcha8', jp: 'ちゅういしてください。', reading: 'chuui shite kudasai.', translation: { es: 'Tenga cuidado, por favor.', en: 'Be careful, please.' } },
    ],
  },
  {
    id: 'hiragana-nya',
    kind: 'hiragana',
    chars: 'にゃにゅにょ',
    sentences: [
      { id: 'hnya1', jp: 'こんにゃくをたべます。', reading: 'konnyaku wo tabemasu.', translation: { es: 'Como konjac.', en: 'I eat konjac.' } },
      { id: 'hnya2', jp: 'にゅうがくしました。', reading: 'nyuugaku shimashita.', translation: { es: 'Ingresé a la escuela.', en: 'I entered school.' } },
      { id: 'hnya3', jp: 'ねこがにゃあとなきます。', reading: 'neko ga nyaa to nakimasu.', translation: { es: 'El gato maúlla.', en: 'The cat meows.' } },
      { id: 'hnya4', jp: 'ぎゅうにゅうをのみます。', reading: 'gyuunyuu wo nomimasu.', translation: { es: 'Tomo leche.', en: 'I drink milk.' } },
      { id: 'hnya5', jp: 'にゅうよくします。', reading: 'nyuuyoku shimasu.', translation: { es: 'Me baño.', en: 'I take a bath.' } },
    ],
  },
  {
    id: 'hiragana-hya',
    kind: 'hiragana',
    chars: 'ひゃひゅひょ',
    sentences: [
      { id: 'hhya1', jp: 'ひゃくえんです。', reading: 'hyaku en desu.', translation: { es: 'Son 100 yenes.', en: 'It\'s 100 yen.' } },
      { id: 'hhya2', jp: 'ひょうがふります。', reading: 'hyou ga furimasu.', translation: { es: 'Cae granizo.', en: 'Hail falls.' } },
      { id: 'hhya3', jp: 'ひゃっかてんにいきます。', reading: 'hyakkaten ni ikimasu.', translation: { es: 'Voy a la tienda por departamentos.', en: 'I go to the department store.' } },
      { id: 'hhya4', jp: 'ひょうじょうがいいです。', reading: 'hyoujou ga ii desu.', translation: { es: 'Tiene buena expresión.', en: 'He has a good expression.' } },
      { id: 'hhya5', jp: 'かぜがひゅうとふきます。', reading: 'kaze ga hyuu to fukimasu.', translation: { es: 'El viento sopla con un silbido.', en: 'The wind blows with a whistle.' } },
    ],
  },
  {
    id: 'hiragana-mya',
    kind: 'hiragana',
    chars: 'みゃみゅみょ',
    sentences: [
      { id: 'hmya1', jp: 'みょうじをおしえてください。', reading: 'myouji wo oshiete kudasai.', translation: { es: 'Dígame su apellido, por favor.', en: 'Tell me your last name, please.' } },
      { id: 'hmya2', jp: 'みゃくがはやいです。', reading: 'myaku ga hayai desu.', translation: { es: 'El pulso está rápido.', en: 'The pulse is fast.' } },
    ],
  },
  {
    id: 'hiragana-rya',
    kind: 'hiragana',
    chars: 'りゃりゅりょ',
    sentences: [
      { id: 'hrya1', jp: 'りょこうにいきます。', reading: 'ryokou ni ikimasu.', translation: { es: 'Voy de viaje.', en: 'I go on a trip.' } },
      { id: 'hrya2', jp: 'りょうりをつくります。', reading: 'ryouri wo tsukurimasu.', translation: { es: 'Cocino.', en: 'I cook.' } },
      { id: 'hrya3', jp: 'りょうしんとすんでいます。', reading: 'ryoushin to sundeimasu.', translation: { es: 'Vivo con mis padres.', en: 'I live with my parents.' } },
      { id: 'hrya4', jp: 'りゅうがすきです。', reading: 'ryuu ga suki desu.', translation: { es: 'Me gustan los dragones.', en: 'I like dragons.' } },
      { id: 'hrya5', jp: 'りょかんにとまります。', reading: 'ryokan ni tomarimasu.', translation: { es: 'Me alojo en un ryokan.', en: 'I stay at a ryokan.' } },
      { id: 'hrya6', jp: 'りょうがえをします。', reading: 'ryougae wo shimasu.', translation: { es: 'Hago cambio de moneda.', en: 'I exchange currency.' } },
    ],
  },
  {
    id: 'hiragana-gya',
    kind: 'hiragana',
    chars: 'ぎゃぎゅぎょ',
    sentences: [
      { id: 'hgya1', jp: 'ぎゃくにしてください。', reading: 'gyaku ni shite kudasai.', translation: { es: 'Hágalo al revés, por favor.', en: 'Do it backwards, please.' } },
      { id: 'hgya2', jp: 'ぎゅうにゅうをのみます。', reading: 'gyuunyuu wo nomimasu.', translation: { es: 'Tomo leche.', en: 'I drink milk.' } },
      { id: 'hgya3', jp: 'ぎょせんがみえます。', reading: 'gyosen ga miemasu.', translation: { es: 'Se ve un barco pesquero.', en: 'A fishing boat can be seen.' } },
      { id: 'hgya4', jp: 'きんぎょをかいます。', reading: 'kingyo wo kaimasu.', translation: { es: 'Compro un pez dorado.', en: 'I buy a goldfish.' } },
    ],
  },
  {
    id: 'hiragana-ja',
    kind: 'hiragana',
    chars: 'じゃじゅじょ',
    sentences: [
      { id: 'hja1', jp: 'じゃがいもがすきです。', reading: 'jagaimo ga suki desu.', translation: { es: 'Me gustan las papas.', en: 'I like potatoes.' } },
      { id: 'hja2', jp: 'じゅぎょうがあります。', reading: 'jugyou ga arimasu.', translation: { es: 'Tengo clase.', en: 'I have class.' } },
      { id: 'hja3', jp: 'にほんごがじょうずです。', reading: 'nihongo ga jouzu desu.', translation: { es: 'Es hábil en japonés.', en: 'He is skilled at Japanese.' } },
      { id: 'hja4', jp: 'おじゃまします。', reading: 'ojama shimasu.', translation: { es: 'Con permiso, al entrar.', en: 'Excuse me, when entering.' } },
      { id: 'hja5', jp: 'じゅうしょをおしえてください。', reading: 'juusho wo oshiete kudasai.', translation: { es: 'Dígame su dirección, por favor.', en: 'Tell me your address, please.' } },
      { id: 'hja6', jp: 'じょうたいがいいです。', reading: 'joutai ga ii desu.', translation: { es: 'Está en buen estado.', en: 'It\'s in good condition.' } },
      { id: 'hja7', jp: 'じゃんけんをします。', reading: 'janken wo shimasu.', translation: { es: 'Juego a piedra, papel o tijera.', en: 'I play rock, paper, scissors.' } },
      { id: 'hja8', jp: 'じゅんびができました。', reading: 'junbi ga dekimashita.', translation: { es: 'Está listo.', en: 'It\'s ready.' } },
    ],
  },
  {
    id: 'hiragana-bya',
    kind: 'hiragana',
    chars: 'びゃびゅびょ',
    sentences: [
      { id: 'hbya1', jp: 'びょういんにいきます。', reading: 'byouin ni ikimasu.', translation: { es: 'Voy al hospital.', en: 'I go to the hospital.' } },
      { id: 'hbya2', jp: 'びょうきです。', reading: 'byouki desu.', translation: { es: 'Estoy enfermo.', en: 'I am sick.' } },
      { id: 'hbya3', jp: 'さんびゃくえんです。', reading: 'sanbyaku en desu.', translation: { es: 'Son 300 yenes.', en: 'It\'s 300 yen.' } },
    ],
  },
  {
    id: 'hiragana-pya',
    kind: 'hiragana',
    chars: 'ぴゃぴゅぴょ',
    sentences: [
      { id: 'hpya1', jp: 'はっぴゃくえんです。', reading: 'happyaku en desu.', translation: { es: 'Son 800 yenes.', en: 'It\'s 800 yen.' } },
      { id: 'hpya2', jp: 'ぴょんぴょんとびます。', reading: 'pyonpyon tobimasu.', translation: { es: 'Salta dando saltitos.', en: 'It hops around.' } },
    ],
  },
  {
    id: 'hiragana-sa',
    kind: 'hiragana',
    chars: 'さしすせそ',
    sentences: [
      { id: 'h1', jp: 'さかながすきです。', reading: 'sakana ga suki desu.', translation: { es: 'Me gusta el pescado.', en: 'I like fish.' } },
      { id: 'h2', jp: 'すしをたべます。', reading: 'sushi wo tabemasu.', translation: { es: 'Como sushi.', en: 'I eat sushi.' } },
      { id: 'h3', jp: 'あさです。', reading: 'asa desu.', translation: { es: 'Es de mañana.', en: 'It\'s morning.' } },
      { id: 'h4', jp: 'せんせいはやさしいです。', reading: 'sensei wa yasashii desu.', translation: { es: 'El profesor es amable.', en: 'The teacher is kind.' } },
      { id: 'h5', jp: 'そらはあおいです。', reading: 'sora wa aoi desu.', translation: { es: 'El cielo es azul.', en: 'The sky is blue.' } },
      { id: 'h6', jp: 'すこしまってください。', reading: 'sukoshi matte kudasai.', translation: { es: 'Espera un poco, por favor.', en: 'Wait a moment, please.' } },
      { id: 'h7', jp: 'せかいはひろいです。', reading: 'sekai wa hiroi desu.', translation: { es: 'El mundo es grande.', en: 'The world is big.' } },
      { id: 'h8', jp: 'すいかはあまいです。', reading: 'suika wa amai desu.', translation: { es: 'La sandía es dulce.', en: 'The watermelon is sweet.' } },
      { id: 'h9', jp: 'きのうはさむかったです。', reading: 'kinou wa samukatta desu.', translation: { es: 'Ayer hizo frío.', en: 'It was cold yesterday.' } },
      { id: 'h10', jp: 'しずかにしてください。', reading: 'shizuka ni shite kudasai.', translation: { es: 'Guarda silencio, por favor.', en: 'Keep quiet, please.' } },
      { id: 'h11', jp: 'さいふをなくしました。', reading: 'saifu wo nakushimashita.', translation: { es: 'Perdí la billetera.', en: 'I lost my wallet.' } },
      { id: 'h12', jp: 'すずしいですね。', reading: 'suzushii desu ne.', translation: { es: 'Qué fresco, ¿no?', en: 'It\'s cool, isn\'t it?' } },
    ],
  },
  {
    id: 'katakana-a',
    kind: 'katakana',
    chars: 'アイウエオ',
    sentences: [
      { id: 'ka1', jp: 'アイスをたべます。', reading: 'aisu wo tabemasu.', translation: { es: 'Como helado.', en: 'I eat ice cream.' } },
      { id: 'ka2', jp: 'イヤホンをつけます。', reading: 'iyahon wo tsukemasu.', translation: { es: 'Me pongo los auriculares.', en: 'I put on the headphones.' } },
      { id: 'ka3', jp: 'ウイスキーをのみます。', reading: 'uisukii wo nomimasu.', translation: { es: 'Tomo whisky.', en: 'I drink whisky.' } },
      { id: 'ka4', jp: 'エレベーターでいきます。', reading: 'erebeetaa de ikimasu.', translation: { es: 'Voy en ascensor.', en: 'I go by elevator.' } },
      { id: 'ka5', jp: 'オレンジがすきです。', reading: 'orenji ga suki desu.', translation: { es: 'Me gusta la naranja.', en: 'I like oranges.' } },
      { id: 'ka6', jp: 'アパートにすんでいます。', reading: 'apaato ni sundeimasu.', translation: { es: 'Vivo en un apartamento.', en: 'I live in an apartment.' } },
      { id: 'ka7', jp: 'アニメをみます。', reading: 'anime wo mimasu.', translation: { es: 'Veo anime.', en: 'I watch anime.' } },
      { id: 'ka8', jp: 'イメージがちがいます。', reading: 'imeeji ga chigaimasu.', translation: { es: 'La imagen es diferente.', en: 'The image is different.' } },
      { id: 'ka9', jp: 'ウールのセーターです。', reading: 'uuru no seetaa desu.', translation: { es: 'Es un suéter de lana.', en: 'It is a wool sweater.' } },
      { id: 'ka10', jp: 'オフィスではたらきます。', reading: 'ofisu de hatarakimasu.', translation: { es: 'Trabajo en la oficina.', en: 'I work at the office.' } },
    ],
  },
  {
    id: 'katakana-ka',
    kind: 'katakana',
    chars: 'カキクケコ',
    sentences: [
      { id: 'kka1', jp: 'カメラをかいました。', reading: 'kamera wo kaimashita.', translation: { es: 'Compré una cámara.', en: 'I bought a camera.' } },
      { id: 'kka2', jp: 'キーをなくしました。', reading: 'kii wo nakushimashita.', translation: { es: 'Perdí la llave.', en: 'I lost the key.' } },
      { id: 'kka3', jp: 'クッキーをたべます。', reading: 'kukkii wo tabemasu.', translation: { es: 'Como galletas.', en: 'I eat cookies.' } },
      { id: 'kka4', jp: 'ケーキがおいしいです。', reading: 'keeki ga oishii desu.', translation: { es: 'El pastel está rico.', en: 'The cake is delicious.' } },
      { id: 'kka5', jp: 'コーヒーをのみます。', reading: 'koohii wo nomimasu.', translation: { es: 'Tomo café.', en: 'I drink coffee.' } },
      { id: 'kka6', jp: 'カレーがすきです。', reading: 'karee ga suki desu.', translation: { es: 'Me gusta el curry.', en: 'I like curry.' } },
      { id: 'kka7', jp: 'カードではらいます。', reading: 'kaado de haraimasu.', translation: { es: 'Pago con tarjeta.', en: 'I pay with a card.' } },
      { id: 'kka8', jp: 'クラスがはじまります。', reading: 'kurasu ga hajimarimasu.', translation: { es: 'Empieza la clase.', en: 'Class starts.' } },
      { id: 'kka9', jp: 'ケースにいれます。', reading: 'keesu ni iremasu.', translation: { es: 'Lo pongo en el estuche.', en: 'I put it in the case.' } },
      { id: 'kka10', jp: 'コンピューターをつかいます。', reading: 'konpyuutaa wo tsukaimasu.', translation: { es: 'Uso la computadora.', en: 'I use the computer.' } },
    ],
  },
  {
    id: 'katakana-ta',
    kind: 'katakana',
    chars: 'タチツテト',
    sentences: [
      { id: 'kta1', jp: 'タクシーをよびます。', reading: 'takushii wo yobimasu.', translation: { es: 'Llamo un taxi.', en: 'I call a taxi.' } },
      { id: 'kta2', jp: 'チームにはいります。', reading: 'chiimu ni hairimasu.', translation: { es: 'Me uno al equipo.', en: 'I join the team.' } },
      { id: 'kta3', jp: 'ツアーにさんかします。', reading: 'tsuaa ni sankashimasu.', translation: { es: 'Participo en un tour.', en: 'I take part in a tour.' } },
      { id: 'kta4', jp: 'テレビをみます。', reading: 'terebi wo mimasu.', translation: { es: 'Veo televisión.', en: 'I watch television.' } },
      { id: 'kta5', jp: 'トマトをかいました。', reading: 'tomato wo kaimashita.', translation: { es: 'Compré tomates.', en: 'I bought tomatoes.' } },
      { id: 'kta6', jp: 'タオルをください。', reading: 'taoru wo kudasai.', translation: { es: 'Una toalla, por favor.', en: 'A towel, please.' } },
      { id: 'kta7', jp: 'テストがむずかしかったです。', reading: 'tesuto ga muzukashikatta desu.', translation: { es: 'El examen estuvo difícil.', en: 'The exam was hard.' } },
      { id: 'kta8', jp: 'トイレはどこですか。', reading: 'toire wa doko desu ka.', translation: { es: '¿Dónde está el baño?', en: 'Where is the bathroom?' } },
      { id: 'kta9', jp: 'チケットをかいました。', reading: 'chiketto wo kaimashita.', translation: { es: 'Compré un boleto.', en: 'I bought a ticket.' } },
      { id: 'kta10', jp: 'テーブルにおきます。', reading: 'teeburu ni okimasu.', translation: { es: 'Lo pongo en la mesa.', en: 'I put it on the table.' } },
    ],
  },
  {
    id: 'katakana-na',
    kind: 'katakana',
    chars: 'ナニヌネノ',
    sentences: [
      { id: 'kna1', jp: 'ナイフをつかいます。', reading: 'naifu wo tsukaimasu.', translation: { es: 'Uso el cuchillo.', en: 'I use the knife.' } },
      { id: 'kna2', jp: 'ニュースをみます。', reading: 'nyuusu wo mimasu.', translation: { es: 'Veo las noticias.', en: 'I watch the news.' } },
      { id: 'kna3', jp: 'ヌードルがすきです。', reading: 'nuudoru ga suki desu.', translation: { es: 'Me gustan los fideos instantáneos.', en: 'I like instant noodles.' } },
      { id: 'kna4', jp: 'ネクタイをします。', reading: 'nekutai wo shimasu.', translation: { es: 'Me pongo la corbata.', en: 'I put on the tie.' } },
      { id: 'kna5', jp: 'ノートをかいました。', reading: 'nooto wo kaimashita.', translation: { es: 'Compré un cuaderno.', en: 'I bought a notebook.' } },
      { id: 'kna6', jp: 'ナンバーをおしえてください。', reading: 'nanbaa wo oshiete kudasai.', translation: { es: 'Dígame el número, por favor.', en: 'Tell me the number, please.' } },
      { id: 'kna7', jp: 'ナポリタンをたべます。', reading: 'naporitan wo tabemasu.', translation: { es: 'Como espagueti napolitana.', en: 'I eat napolitan spaghetti.' } },
      { id: 'kna8', jp: 'ネットでしらべます。', reading: 'netto de shirabemasu.', translation: { es: 'Busco en internet.', en: 'I search on the internet.' } },
      { id: 'kna9', jp: 'ノックしてください。', reading: 'nokku shite kudasai.', translation: { es: 'Toque la puerta, por favor.', en: 'Knock on the door, please.' } },
      { id: 'kna10', jp: 'ニットがあたたかいです。', reading: 'nitto ga atatakai desu.', translation: { es: 'El suéter tejido es abrigado.', en: 'The knit sweater is warm.' } },
    ],
  },
  {
    id: 'katakana-ha',
    kind: 'katakana',
    chars: 'ハヒフヘホ',
    sentences: [
      { id: 'kha1', jp: 'ハンカチをわすれました。', reading: 'hankachi wo wasuremashita.', translation: { es: 'Me olvidé el pañuelo.', en: 'I forgot my handkerchief.' } },
      { id: 'kha2', jp: 'ヒーターをつけます。', reading: 'hiitaa wo tsukemasu.', translation: { es: 'Prendo el calefactor.', en: 'I turn on the heater.' } },
      { id: 'kha3', jp: 'フォークをつかいます。', reading: 'fooku wo tsukaimasu.', translation: { es: 'Uso el tenedor.', en: 'I use the fork.' } },
      { id: 'kha4', jp: 'ヘアスタイルをかえました。', reading: 'heasutairu wo kaemashita.', translation: { es: 'Cambié de peinado.', en: 'I changed my hairstyle.' } },
      { id: 'kha5', jp: 'ホテルにとまります。', reading: 'hoteru ni tomarimasu.', translation: { es: 'Me alojo en un hotel.', en: 'I stay at a hotel.' } },
      { id: 'kha6', jp: 'ハンバーガーをたべます。', reading: 'hanbaagaa wo tabemasu.', translation: { es: 'Como una hamburguesa.', en: 'I eat a hamburger.' } },
      { id: 'kha7', jp: 'ヒントをください。', reading: 'hinto wo kudasai.', translation: { es: 'Deme una pista, por favor.', en: 'Give me a hint, please.' } },
      { id: 'kha8', jp: 'フルーツがすきです。', reading: 'furuutsu ga suki desu.', translation: { es: 'Me gusta la fruta.', en: 'I like fruit.' } },
      { id: 'kha9', jp: 'ヘルメットをかぶります。', reading: 'herumetto wo kaburimasu.', translation: { es: 'Me pongo el casco.', en: 'I put on the helmet.' } },
      { id: 'kha10', jp: 'ホームでまちます。', reading: 'hoomu de machimasu.', translation: { es: 'Espero en el andén.', en: 'I wait on the platform.' } },
    ],
  },
  {
    id: 'katakana-ma',
    kind: 'katakana',
    chars: 'マミムメモ',
    sentences: [
      { id: 'kma1', jp: 'マンションにすんでいます。', reading: 'manshon ni sundeimasu.', translation: { es: 'Vivo en un departamento.', en: 'I live in an apartment.' } },
      { id: 'kma2', jp: 'ミルクをのみます。', reading: 'miruku wo nomimasu.', translation: { es: 'Tomo leche.', en: 'I drink milk.' } },
      { id: 'kma3', jp: 'ムードがいいです。', reading: 'muudo ga ii desu.', translation: { es: 'Hay buen ambiente.', en: 'There is a good atmosphere.' } },
      { id: 'kma4', jp: 'メニューをください。', reading: 'menyuu wo kudasai.', translation: { es: 'El menú, por favor.', en: 'The menu, please.' } },
      { id: 'kma5', jp: 'モデルになりたいです。', reading: 'moderu ni naritai desu.', translation: { es: 'Quiero ser modelo.', en: 'I want to be a model.' } },
      { id: 'kma6', jp: 'マスクをします。', reading: 'masuku wo shimasu.', translation: { es: 'Me pongo el barbijo.', en: 'I put on the mask.' } },
      { id: 'kma7', jp: 'ミーティングがあります。', reading: 'miitingu ga arimasu.', translation: { es: 'Hay una reunión.', en: 'There is a meeting.' } },
      { id: 'kma8', jp: 'メールをおくります。', reading: 'meeru wo okurimasu.', translation: { es: 'Mando un mail.', en: 'I send an email.' } },
      { id: 'kma9', jp: 'モニターがおおきいです。', reading: 'monitaa ga ookii desu.', translation: { es: 'El monitor es grande.', en: 'The monitor is big.' } },
      { id: 'kma10', jp: 'マラソンをはしります。', reading: 'marason wo hashirimasu.', translation: { es: 'Corro un maratón.', en: 'I run a marathon.' } },
    ],
  },
  {
    id: 'katakana-ya',
    kind: 'katakana',
    chars: 'ヤユヨ',
    sentences: [
      { id: 'kya1', jp: 'タイヤがパンクしました。', reading: 'taiya ga panku shimashita.', translation: { es: 'Se pinchó la rueda.', en: 'The tire got a flat.' } },
      { id: 'kya2', jp: 'ユーモアがあります。', reading: 'yuumoa ga arimasu.', translation: { es: 'Tiene sentido del humor.', en: 'He has a sense of humor.' } },
      { id: 'kya3', jp: 'ヨーロッパにいきたいです。', reading: 'yooroppa ni ikitai desu.', translation: { es: 'Quiero ir a Europa.', en: 'I want to go to Europe.' } },
      { id: 'kya4', jp: 'パパイヤをたべます。', reading: 'papaiya wo tabemasu.', translation: { es: 'Como papaya.', en: 'I eat papaya.' } },
      { id: 'kya5', jp: 'ユニークなデザインです。', reading: 'yuniiku na dezain desu.', translation: { es: 'Es un diseño único.', en: 'It is a unique design.' } },
      { id: 'kya6', jp: 'ヨガをします。', reading: 'yoga wo shimasu.', translation: { es: 'Hago yoga.', en: 'I do yoga.' } },
      { id: 'kya7', jp: 'ダイヤモンドです。', reading: 'daiyamondo desu.', translation: { es: 'Es un diamante.', en: 'It is a diamond.' } },
      { id: 'kya8', jp: 'ヨットにのります。', reading: 'yotto ni norimasu.', translation: { es: 'Subo a un velero.', en: 'I board a sailboat.' } },
    ],
  },
  {
    id: 'katakana-ra',
    kind: 'katakana',
    chars: 'ラリルレロ',
    sentences: [
      { id: 'kra1', jp: 'ラーメンをたべます。', reading: 'raamen wo tabemasu.', translation: { es: 'Como ramen.', en: 'I eat ramen.' } },
      { id: 'kra2', jp: 'リモコンをください。', reading: 'rimokon wo kudasai.', translation: { es: 'El control remoto, por favor.', en: 'The remote control, please.' } },
      { id: 'kra3', jp: 'ルールをまもります。', reading: 'ruuru wo mamorimasu.', translation: { es: 'Sigo las reglas.', en: 'I follow the rules.' } },
      { id: 'kra4', jp: 'レストランでたべます。', reading: 'resutoran de tabemasu.', translation: { es: 'Como en un restaurante.', en: 'I eat at a restaurant.' } },
      { id: 'kra5', jp: 'ロボットがうごきます。', reading: 'robotto ga ugokimasu.', translation: { es: 'El robot se mueve.', en: 'The robot moves.' } },
      { id: 'kra6', jp: 'ライトをつけます。', reading: 'raito wo tsukemasu.', translation: { es: 'Prendo la luz.', en: 'I turn on the light.' } },
      { id: 'kra7', jp: 'リストをつくります。', reading: 'risuto wo tsukurimasu.', translation: { es: 'Hago una lista.', en: 'I make a list.' } },
      { id: 'kra8', jp: 'レモンがすっぱいです。', reading: 'remon ga suppai desu.', translation: { es: 'El limón es ácido.', en: 'The lemon is sour.' } },
      { id: 'kra9', jp: 'ロビーでまちます。', reading: 'robii de machimasu.', translation: { es: 'Espero en el lobby.', en: 'I wait in the lobby.' } },
      { id: 'kra10', jp: 'ラジオをききます。', reading: 'rajio wo kikimasu.', translation: { es: 'Escucho la radio.', en: 'I listen to the radio.' } },
    ],
  },
  {
    id: 'katakana-wa',
    kind: 'katakana',
    chars: 'ワヲ',
    sentences: [
      { id: 'kwa1', jp: 'ワインをのみます。', reading: 'wain wo nomimasu.', translation: { es: 'Tomo vino.', en: 'I drink wine.' } },
      { id: 'kwa2', jp: 'ワイシャツをきます。', reading: 'waishatsu wo kimasu.', translation: { es: 'Me pongo la camisa.', en: 'I put on the shirt.' } },
      { id: 'kwa3', jp: 'ワンピースをかいました。', reading: 'wanpiisu wo kaimashita.', translation: { es: 'Compré un vestido.', en: 'I bought a dress.' } },
      { id: 'kwa4', jp: 'ワッフルがすきです。', reading: 'waffuru ga suki desu.', translation: { es: 'Me gustan los waffles.', en: 'I like waffles.' } },
      { id: 'kwa5', jp: 'ワクチンをうけました。', reading: 'wakuchin wo ukemashita.', translation: { es: 'Me di la vacuna.', en: 'I got the vaccine.' } },
      { id: 'kwa6', jp: 'ワイヤレスイヤホンです。', reading: 'waiyaresu iyahon desu.', translation: { es: 'Son auriculares inalámbricos.', en: 'They are wireless headphones.' } },
      { id: 'kwa7', jp: 'ハワイにいきたいです。', reading: 'hawai ni ikitai desu.', translation: { es: 'Quiero ir a Hawái.', en: 'I want to go to Hawaii.' } },
    ],
  },
  {
    id: 'katakana-n',
    kind: 'katakana',
    chars: 'ン',
    sentences: [
      { id: 'kn1', jp: 'パンをかいます。', reading: 'pan wo kaimasu.', translation: { es: 'Compro pan.', en: 'I buy bread.' } },
      { id: 'kn2', jp: 'ペンをかしてください。', reading: 'pen wo kashite kudasai.', translation: { es: 'Préstame un bolígrafo, por favor.', en: 'Lend me a pen, please.' } },
      { id: 'kn3', jp: 'ボタンをおします。', reading: 'botan wo oshimasu.', translation: { es: 'Aprieto el botón.', en: 'I press the button.' } },
      { id: 'kn4', jp: 'レストランにいきます。', reading: 'resutoran ni ikimasu.', translation: { es: 'Voy a un restaurante.', en: 'I go to a restaurant.' } },
      { id: 'kn5', jp: 'スプーンをつかいます。', reading: 'supuun wo tsukaimasu.', translation: { es: 'Uso la cuchara.', en: 'I use the spoon.' } },
      { id: 'kn6', jp: 'ファッションがすきです。', reading: 'fasshon ga suki desu.', translation: { es: 'Me gusta la moda.', en: 'I like fashion.' } },
      { id: 'kn7', jp: 'ライオンをみました。', reading: 'raion wo mimashita.', translation: { es: 'Vi un león.', en: 'I saw a lion.' } },
      { id: 'kn8', jp: 'サンドイッチをたべます。', reading: 'sandoicchi wo tabemasu.', translation: { es: 'Como un sándwich.', en: 'I eat a sandwich.' } },
      { id: 'kn9', jp: 'コンサートにいきます。', reading: 'konsaato ni ikimasu.', translation: { es: 'Voy a un concierto.', en: 'I go to a concert.' } },
      { id: 'kn10', jp: 'デザインがいいです。', reading: 'dezain ga ii desu.', translation: { es: 'El diseño es bueno.', en: 'The design is good.' } },
    ],
  },
  {
    id: 'katakana-ga',
    kind: 'katakana',
    chars: 'ガギグゲゴ',
    sentences: [
      { id: 'kga1', jp: 'ガムをかみます。', reading: 'gamu wo kamimasu.', translation: { es: 'Mastico chicle.', en: 'I chew gum.' } },
      { id: 'kga2', jp: 'ギターをひきます。', reading: 'gitaa wo hikimasu.', translation: { es: 'Toco la guitarra.', en: 'I play the guitar.' } },
      { id: 'kga3', jp: 'グラスをください。', reading: 'gurasu wo kudasai.', translation: { es: 'Un vaso, por favor.', en: 'A glass, please.' } },
      { id: 'kga4', jp: 'ゲームをします。', reading: 'geemu wo shimasu.', translation: { es: 'Juego videojuegos.', en: 'I play video games.' } },
      { id: 'kga5', jp: 'ゴルフをします。', reading: 'gorufu wo shimasu.', translation: { es: 'Juego al golf.', en: 'I play golf.' } },
      { id: 'kga6', jp: 'ガソリンがひつようです。', reading: 'gasorin ga hitsuyou desu.', translation: { es: 'Necesito nafta.', en: 'I need gas.' } },
      { id: 'kga7', jp: 'ガイドをよみます。', reading: 'gaido wo yomimasu.', translation: { es: 'Leo la guía.', en: 'I read the guide.' } },
      { id: 'kga8', jp: 'ゴールにつきました。', reading: 'gooru ni tsukimashita.', translation: { es: 'Llegué a la meta.', en: 'I reached the finish line.' } },
    ],
  },
  {
    id: 'katakana-za',
    kind: 'katakana',
    chars: 'ザジズゼゾ',
    sentences: [
      { id: 'kza1', jp: 'デザートをたべます。', reading: 'dezaato wo tabemasu.', translation: { es: 'Como postre.', en: 'I eat dessert.' } },
      { id: 'kza2', jp: 'サイズをはかります。', reading: 'saizu wo hakarimasu.', translation: { es: 'Mido el tamaño.', en: 'I measure the size.' } },
      { id: 'kza3', jp: 'ジーンズをはきます。', reading: 'jiinzu wo hakimasu.', translation: { es: 'Me pongo los jeans.', en: 'I put on jeans.' } },
      { id: 'kza4', jp: 'ゼロからはじめます。', reading: 'zero kara hajimemasu.', translation: { es: 'Empiezo desde cero.', en: 'I start from zero.' } },
      { id: 'kza5', jp: 'カジノにいきます。', reading: 'kajino ni ikimasu.', translation: { es: 'Voy a un casino.', en: 'I go to a casino.' } },
      { id: 'kza6', jp: 'ズボンをかいました。', reading: 'zubon wo kaimashita.', translation: { es: 'Compré pantalones.', en: 'I bought pants.' } },
      { id: 'kza7', jp: 'マガジンをよみます。', reading: 'magajin wo yomimasu.', translation: { es: 'Leo una revista.', en: 'I read a magazine.' } },
      { id: 'kza8', jp: 'ジムにいきます。', reading: 'jimu ni ikimasu.', translation: { es: 'Voy al gimnasio.', en: 'I go to the gym.' } },
    ],
  },
  {
    id: 'katakana-da',
    kind: 'katakana',
    chars: 'ダヂヅデド',
    sentences: [
      { id: 'kda1', jp: 'ドアをあけます。', reading: 'doa wo akemasu.', translation: { es: 'Abro la puerta.', en: 'I open the door.' } },
      { id: 'kda2', jp: 'デザインがいいです。', reading: 'dezain ga ii desu.', translation: { es: 'El diseño es bueno.', en: 'The design is good.' } },
      { id: 'kda3', jp: 'ダイエットをします。', reading: 'daietto wo shimasu.', translation: { es: 'Hago dieta.', en: 'I diet.' } },
      { id: 'kda4', jp: 'カードをつかいます。', reading: 'kaado wo tsukaimasu.', translation: { es: 'Uso la tarjeta.', en: 'I use the card.' } },
      { id: 'kda5', jp: 'ハンドルをもちます。', reading: 'handoru wo mochimasu.', translation: { es: 'Sostengo el volante.', en: 'I hold the steering wheel.' } },
      { id: 'kda6', jp: 'ダンスをします。', reading: 'dansu wo shimasu.', translation: { es: 'Bailo.', en: 'I dance.' } },
      { id: 'kda7', jp: 'レモネードをのみます。', reading: 'remoneedo wo nomimasu.', translation: { es: 'Tomo limonada.', en: 'I drink lemonade.' } },
      { id: 'kda8', jp: 'デートにいきます。', reading: 'deeto ni ikimasu.', translation: { es: 'Voy a una cita.', en: 'I go on a date.' } },
    ],
  },
  {
    id: 'katakana-ba',
    kind: 'katakana',
    chars: 'バビブベボ',
    sentences: [
      { id: 'kba1', jp: 'バスにのります。', reading: 'basu ni norimasu.', translation: { es: 'Subo al bus.', en: 'I get on the bus.' } },
      { id: 'kba2', jp: 'テレビをみます。', reading: 'terebi wo mimasu.', translation: { es: 'Veo la tele.', en: 'I watch TV.' } },
      { id: 'kba3', jp: 'ベッドでねます。', reading: 'beddo de nemasu.', translation: { es: 'Duermo en la cama.', en: 'I sleep in the bed.' } },
      { id: 'kba4', jp: 'ボールをなげます。', reading: 'booru wo nagemasu.', translation: { es: 'Tiro la pelota.', en: 'I throw the ball.' } },
      { id: 'kba5', jp: 'バナナをたべます。', reading: 'banana wo tabemasu.', translation: { es: 'Como banana.', en: 'I eat a banana.' } },
      { id: 'kba6', jp: 'バイクにのります。', reading: 'baiku ni norimasu.', translation: { es: 'Subo a la moto.', en: 'I get on the motorcycle.' } },
      { id: 'kba7', jp: 'アルバイトをします。', reading: 'arubaito wo shimasu.', translation: { es: 'Trabajo medio tiempo.', en: 'I work part-time.' } },
      { id: 'kba8', jp: 'バターをぬります。', reading: 'bataa wo nurimasu.', translation: { es: 'Unto manteca.', en: 'I spread butter.' } },
    ],
  },
  {
    id: 'katakana-pa',
    kind: 'katakana',
    chars: 'パピプペポ',
    sentences: [
      { id: 'kpa1', jp: 'パンをたべます。', reading: 'pan wo tabemasu.', translation: { es: 'Como pan.', en: 'I eat bread.' } },
      { id: 'kpa2', jp: 'スーパーにいきます。', reading: 'suupaa ni ikimasu.', translation: { es: 'Voy al supermercado.', en: 'I go to the supermarket.' } },
      { id: 'kpa3', jp: 'パーティーにいきます。', reading: 'paatii ni ikimasu.', translation: { es: 'Voy a una fiesta.', en: 'I go to a party.' } },
      { id: 'kpa4', jp: 'ペンキをぬります。', reading: 'penki wo nurimasu.', translation: { es: 'Pinto con pintura.', en: 'I paint with paint.' } },
      { id: 'kpa5', jp: 'パスポートをみせてください。', reading: 'pasupooto wo misete kudasai.', translation: { es: 'Muestre el pasaporte, por favor.', en: 'Show your passport, please.' } },
      { id: 'kpa6', jp: 'ポケットにいれます。', reading: 'poketto ni iremasu.', translation: { es: 'Lo pongo en el bolsillo.', en: 'I put it in my pocket.' } },
      { id: 'kpa7', jp: 'サポートがひつようです。', reading: 'sapooto ga hitsuyou desu.', translation: { es: 'Necesito ayuda.', en: 'I need help.' } },
      { id: 'kpa8', jp: 'プレゼントをかいました。', reading: 'purezento wo kaimashita.', translation: { es: 'Compré un regalo.', en: 'I bought a gift.' } },
    ],
  },
  {
    id: 'katakana-kya',
    kind: 'katakana',
    chars: 'キャキュキョ',
    sentences: [
      { id: 'kkya1', jp: 'キャベツをかいました。', reading: 'kyabetsu wo kaimashita.', translation: { es: 'Compré repollo.', en: 'I bought cabbage.' } },
      { id: 'kkya2', jp: 'キャンプにいきます。', reading: 'kyanpu ni ikimasu.', translation: { es: 'Voy de campamento.', en: 'I go camping.' } },
      { id: 'kkya3', jp: 'キューをつかいます。', reading: 'kyuu wo tsukaimasu.', translation: { es: 'Uso el taco de billar.', en: 'I use the pool cue.' } },
      { id: 'kkya4', jp: 'キャンセルしました。', reading: 'kyanseru shimashita.', translation: { es: 'Cancelé.', en: 'I cancelled.' } },
      { id: 'kkya5', jp: 'キャプテンです。', reading: 'kyaputen desu.', translation: { es: 'Es el capitán.', en: 'He is the captain.' } },
    ],
  },
  {
    id: 'katakana-sha',
    kind: 'katakana',
    chars: 'シャシュショ',
    sentences: [
      { id: 'ksha1', jp: 'シャワーをあびます。', reading: 'shawaa wo abimasu.', translation: { es: 'Me doy una ducha.', en: 'I take a shower.' } },
      { id: 'ksha2', jp: 'シャツをきます。', reading: 'shatsu wo kimasu.', translation: { es: 'Me pongo la camisa.', en: 'I put on the shirt.' } },
      { id: 'ksha3', jp: 'シュークリームがすきです。', reading: 'shuukuriimu ga suki desu.', translation: { es: 'Me gusta la crema pastelera.', en: 'I like cream puffs.' } },
      { id: 'ksha4', jp: 'ショッピングをします。', reading: 'shoppingu wo shimasu.', translation: { es: 'Voy de compras.', en: 'I go shopping.' } },
      { id: 'ksha5', jp: 'シャンプーをつかいます。', reading: 'shanpuu wo tsukaimasu.', translation: { es: 'Uso champú.', en: 'I use shampoo.' } },
      { id: 'ksha6', jp: 'ショートケーキをたべます。', reading: 'shootokeeki wo tabemasu.', translation: { es: 'Como shortcake.', en: 'I eat shortcake.' } },
      { id: 'ksha7', jp: 'シャッターをおします。', reading: 'shattaa wo oshimasu.', translation: { es: 'Aprieto el obturador.', en: 'I press the shutter.' } },
      { id: 'ksha8', jp: 'シャベルをつかいます。', reading: 'shaberu wo tsukaimasu.', translation: { es: 'Uso la pala.', en: 'I use the shovel.' } },
    ],
  },
  {
    id: 'katakana-cha',
    kind: 'katakana',
    chars: 'チャチュチョ',
    sentences: [
      { id: 'kcha1', jp: 'チャンスがあります。', reading: 'chansu ga arimasu.', translation: { es: 'Hay una oportunidad.', en: 'There is an opportunity.' } },
      { id: 'kcha2', jp: 'チャレンジします。', reading: 'charenji shimasu.', translation: { es: 'Lo intento.', en: 'I give it a try.' } },
      { id: 'kcha3', jp: 'チューリップがきれいです。', reading: 'chuurippu ga kirei desu.', translation: { es: 'Los tulipanes son lindos.', en: 'The tulips are pretty.' } },
      { id: 'kcha4', jp: 'チョコレートがすきです。', reading: 'chokoreeto ga suki desu.', translation: { es: 'Me gusta el chocolate.', en: 'I like chocolate.' } },
      { id: 'kcha5', jp: 'チャイムがなります。', reading: 'chaimu ga narimasu.', translation: { es: 'Suena el timbre.', en: 'The doorbell rings.' } },
      { id: 'kcha6', jp: 'チャットをします。', reading: 'chatto wo shimasu.', translation: { es: 'Chateo.', en: 'I chat.' } },
    ],
  },
  {
    id: 'katakana-nya',
    kind: 'katakana',
    chars: 'ニャニュニョ',
    sentences: [
      { id: 'knya1', jp: 'ネコがニャーとなきます。', reading: 'neko ga nyaa to nakimasu.', translation: { es: 'El gato maúlla.', en: 'The cat meows.' } },
      { id: 'knya2', jp: 'ニュアンスがちがいます。', reading: 'nyuansu ga chigaimasu.', translation: { es: 'El matiz es diferente.', en: 'The nuance is different.' } },
      { id: 'knya3', jp: 'マニュアルをよみます。', reading: 'manyuaru wo yomimasu.', translation: { es: 'Leo el manual.', en: 'I read the manual.' } },
    ],
  },
  {
    id: 'katakana-mya',
    kind: 'katakana',
    chars: 'ミャミュミョ',
    sentences: [
      { id: 'kmya1', jp: 'ミュージックをききます。', reading: 'myuujikku wo kikimasu.', translation: { es: 'Escucho música.', en: 'I listen to music.' } },
      { id: 'kmya2', jp: 'ミュージアムにいきます。', reading: 'myuujiamu ni ikimasu.', translation: { es: 'Voy al museo.', en: 'I go to the museum.' } },
    ],
  },
  {
    id: 'katakana-ja',
    kind: 'katakana',
    chars: 'ジャジュジョ',
    sentences: [
      { id: 'kja1', jp: 'ジャムをぬります。', reading: 'jamu wo nurimasu.', translation: { es: 'Unto mermelada.', en: 'I spread jam.' } },
      { id: 'kja2', jp: 'ジャケットをきます。', reading: 'jaketto wo kimasu.', translation: { es: 'Me pongo la campera.', en: 'I put on the jacket.' } },
      { id: 'kja3', jp: 'ジュースをのみます。', reading: 'juusu wo nomimasu.', translation: { es: 'Tomo jugo.', en: 'I drink juice.' } },
      { id: 'kja4', jp: 'ジョギングをします。', reading: 'jogingu wo shimasu.', translation: { es: 'Hago jogging.', en: 'I go jogging.' } },
      { id: 'kja5', jp: 'ジャズがすきです。', reading: 'jazu ga suki desu.', translation: { es: 'Me gusta el jazz.', en: 'I like jazz.' } },
      { id: 'kja6', jp: 'ジャンプします。', reading: 'janpu shimasu.', translation: { es: 'Salto.', en: 'I jump.' } },
      { id: 'kja7', jp: 'ジョークをいいます。', reading: 'jooku wo iimasu.', translation: { es: 'Digo un chiste.', en: 'I tell a joke.' } },
    ],
  },
  {
    id: 'katakana-sa',
    kind: 'katakana',
    chars: 'サシスセソ',
    sentences: [
      { id: 'k1', jp: 'サラダをたべます。', reading: 'sarada wo tabemasu.', translation: { es: 'Como ensalada.', en: 'I eat salad.' } },
      { id: 'k2', jp: 'すしとステーキがすきです。', reading: 'sushi to suteeki ga suki desu.', translation: { es: 'Me gustan el sushi y el bistec.', en: 'I like sushi and steak.' } },
      { id: 'k3', jp: 'セーターをきます。', reading: 'seetaa wo kimasu.', translation: { es: 'Me pongo el suéter.', en: 'I put on the sweater.' } },
      { id: 'k4', jp: 'スープがあついです。', reading: 'suupu ga atsui desu.', translation: { es: 'La sopa está caliente.', en: 'The soup is hot.' } },
      { id: 'k5', jp: 'サッカーがすきです。', reading: 'sakkaa ga suki desu.', translation: { es: 'Me gusta el fútbol.', en: 'I like soccer.' } },
      { id: 'k6', jp: 'ソファーでねます。', reading: 'sofaa de nemasu.', translation: { es: 'Duermo en el sofá.', en: 'I sleep on the couch.' } },
      { id: 'k7', jp: 'スカートをかいました。', reading: 'sukaato wo kaimashita.', translation: { es: 'Compré una falda.', en: 'I bought a skirt.' } },
      { id: 'k8', jp: 'これはサイズがおおきいです。', reading: 'kore wa saizu ga ookii desu.', translation: { es: 'Esto es de talla grande.', en: 'This is a large size.' } },
      { id: 'k9', jp: 'せんせいはアメリカじんです。', reading: 'sensei wa amerika jin desu.', translation: { es: 'El profesor es estadounidense.', en: 'The teacher is American.' } },
      { id: 'k10', jp: 'スイッチをおしてください。', reading: 'suicchi wo oshite kudasai.', translation: { es: 'Presione el interruptor, por favor.', en: 'Press the switch, please.' } },
      { id: 'k11', jp: 'ソースをかけます。', reading: 'soosu wo kakemasu.', translation: { es: 'Le pongo salsa.', en: 'I put sauce on it.' } },
      { id: 'k12', jp: 'すみません、シャワーはどこですか。', reading: 'sumimasen, shawaa wa doko desu ka.', translation: { es: 'Disculpe, ¿dónde está la ducha?', en: 'Excuse me, where is the shower?' } },
    ],
  },
];

export function getKanaRowPractice(id: string): KanaRowPractice | undefined {
  return KANA_ROW_PRACTICE.find((r) => r.id === id);
}
